name: Figma Modifications

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Check changed files
        uses: tj-actions/changed-files@v29.0.2
        id: changed-files-specific
        with:
          files: |
            tokens.json

      - name: Build tailwind.config
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        run: |
          npm install && npm run build-tw
          git add
          git commit -m "ci(theme): Update tailwind.config.js"
          git push
