name: Figma Modifications

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Changed Files
        uses: tj-actions/changed-files@v29.0.2
        with:
          files: |
            tokens.json
        run: |
          npm install && npm run build-tw
