name: Figma Modifications

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v29.0.2

      - name: Build tailwind.config
        if: contains(steps.changed-files.outputs.modified_files, 'tokens.json')
        run: |
          echo ${{ steps.changed-files-specific.outputs.any_changed }}
          npm install && npm run build-tw
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git config --global user.email "${{ secrets.GH_USERMAIL }}"
          git add -A
          git commit -m "ci(theme): Update tailwind.config.js"
          git push
